Repository kookmin-sw/capstone-2024-17, pull requests merged in 2024-04, with the labels that each got.

#33 [feat] FCM 초기화 및 로직 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/coffee/backend/domain/fcm/controller/FcmController.java
  backend/src/main/java/com/coffee/backend/domain/fcm/dto/FcmPushMessageDto.java
  backend/src/main/java/com/coffee/backend/domain/fcm/dto/FcmRequestDto.java
  backend/src/main/java/com/coffee/backend/domain/fcm/service/FcmService.java
Labels: back-end

#32 #12 init websocket
  backend/build.gradle
  backend/src/main/java/com/coffee/backend/BackendApplication.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/controller/ChatroomController.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/dto/ChatroomCreationDto.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/dto/ChatroomResponse.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/dto/ChatroomResponses.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/entity/Chatroom.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/repository/ChatroomRepository.java
  backend/src/main/java/com/coffee/backend/domain/chatroom/service/ChatroomService.java
  backend/src/main/java/com/coffee/backend/domain/message/controller/MessageController.java
  backend/src/main/java/com/coffee/backend/domain/message/dto/MessageDto.java
  backend/src/main/java/com/coffee/backend/domain/message/dto/MessageResponse.java
  backend/src/main/java/com/coffee/backend/domain/message/dto/MessageResponses.java
  backend/src/main/java/com/coffee/backend/domain/message/entity/Message.java
  backend/src/main/java/com/coffee/backend/domain/message/repository/MessageRepository.java
  backend/src/main/java/com/coffee/backend/domain/message/service/MessageService.java
  backend/src/main/java/com/coffee/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/coffee/backend/domain/userChatroom/entity/UserChatroom.java
  backend/src/main/java/com/coffee/backend/domain/userChatroom/repository/UserChatroomRepository.java
  backend/src/main/java/com/coffee/backend/global/WebSocketConfig.java
Labels: back-end

#40 #3 signin signout
  frontend/android/app/build.gradle
  frontend/assets/logo.png
  frontend/lib/kakao_login.dart
  frontend/lib/login_view_model.dart
  frontend/lib/main.dart
  frontend/lib/screen/login_screen.dart
  frontend/lib/screen/user_screen.dart
  frontend/lib/user_model.dart
  frontend/lib/widgets/bottom_text_secondary_button.dart
  frontend/lib/widgets/iconed_textfield.dart
  frontend/lib/widgets/kakao_login_widget.dart
  frontend/pubspec.yaml
Labels: front-end, ✨ Feature

#41 #39 카페 선택 정보 실시간 업데이트 & 매칭 요청 정보 저장
  backend/build.gradle
  backend/src/main/java/com/coffee/backend/domain/cafe/controller/CafeController.java
  backend/src/main/java/com/coffee/backend/domain/cafe/dto/CafeDto.java
  backend/src/main/java/com/coffee/backend/domain/cafe/service/CafePublisher.java
  backend/src/main/java/com/coffee/backend/domain/cafe/service/CafeSubscriber.java
  backend/src/main/java/com/coffee/backend/domain/match/controller/MatchController.java
  backend/src/main/java/com/coffee/backend/domain/match/dto/MatchDto.java
  backend/src/main/java/com/coffee/backend/domain/match/service/MatchPublisher.java
  backend/src/main/java/com/coffee/backend/domain/match/service/MatchSubscriber.java
  backend/src/main/java/com/coffee/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/coffee/backend/global/RedisConfig.java
  backend/src/main/java/com/coffee/backend/global/WebSocketConfig.java
  backend/src/main/java/com/coffee/backend/global/WebSocketSessionManager.java
Labels: ✨ Feature

#71 GoogleMap 띄우고 주변 카페 불러오기
  .idea/.gitignore
  .idea/flutter_project.iml
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  frontend/.gitignore
  frontend/Usersdnjft.androiddebug.keystore
  frontend/android/app/build.gradle
  frontend/android/app/src/debug/AndroidManifest.xml
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/app/src/main/res/values/styles.xml
  frontend/android/app/src/profile/AndroidManifest.xml
  frontend/android/settings.gradle
  frontend/ios/Runner/AppDelegate.swift
  frontend/ios/Runner/Info.plist
  frontend/lib/screen/map_place.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: ✨ Feature

#78 [feat] 지도 기능 상세 구현
  frontend/android/app/build.gradle
  frontend/lib/screen/map_place.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: ✨ Feature

#104 #2 signup
  frontend/lib/screen/signup_screen.dart
  frontend/lib/screen/signup_screen2.dart
  frontend/lib/screen/signup_screen3.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/iconed_textfield.dart
Labels: ✨ Feature, 🎨 Design

#105 카카오톡 토큰으로 post 요청 #8
  frontend/lib/kakao_login.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/kakao_login_widget.dart
Labels: ✨ Feature

#108 [FEATURE] 지도 필터링 및 기능 구체화
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  frontend/.gitignore
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/app/src/main/res/values/styles.xml
  frontend/lib/model/map_request_dto.dart
  frontend/lib/screen/alarm_list_screen.dart
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/map.dart
  frontend/lib/screen/map_place.dart
  frontend/lib/test.dart
  frontend/lib/widgets/cafe_info.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: ✨ Feature

#115 [feat] 커피챗 평가 저장 API 구현 #101
  backend/src/main/java/com/coffee/backend/domain/match/controller/MatchController.java
  backend/src/main/java/com/coffee/backend/domain/match/dto/ReviewDto.java
  backend/src/main/java/com/coffee/backend/domain/match/entity/Review.java
  backend/src/main/java/com/coffee/backend/domain/match/repository/ReviewRepository.java
  backend/src/main/java/com/coffee/backend/domain/match/service/MatchService.java
  backend/src/main/java/com/coffee/backend/global/RedisConfig.java
Labels: ✨ Feature

#122 [feat] 커피챗 매칭 UI 제작 #116
  frontend/assets/bean(0).png
  frontend/assets/bean(1).png
  frontend/assets/magnifier.png
  frontend/lib/screen/coffeechat_rating_screen.dart
  frontend/lib/screen/matching_screen.dart
  frontend/lib/widgets/alert_dialog_yesno_widget.dart
Labels: ✨ Feature

#123 [feat] 커피 콩점 매기는 기능 구현 #117
  frontend/lib/kakao_login.dart
  frontend/lib/model/map_request_dto.dart
  frontend/lib/screen/alarm_list_screen.dart
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/coffeechat_rating_screen.dart
  frontend/lib/screen/map_place.dart
  frontend/lib/screen/matching_screen.dart
  frontend/lib/test.dart
  frontend/lib/widgets/cafe_info.dart
Labels: ✨ Feature
