Repository kookmin-sw/capstone-2024-17, pull requests merged in 2024-05, with the labels that each got.

#143 [fix] 토큰 형태와 url 수정 #8
  frontend/lib/kakao_login.dart
  frontend/lib/service/api_service.dart
Labels: :bug: Bug

#135 #55 chatting page
  frontend/lib/main.dart
  frontend/lib/screen/chat_screen.dart
  frontend/lib/screen/chatroom_list_screen.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/chat_date.dart
  frontend/lib/widgets/chat_item.dart
  frontend/lib/widgets/chatroom_item.dart
Labels: ✨ Feature, 🎨 Design

#152 [feat] 회사 등록 요청 UI #140
  frontend/lib/screen/add_company_screen.dart
Labels: ✨ Feature, 🎨 Design

#151 #127 select position
  frontend/lib/screen/edit_profile_screen.dart
  frontend/lib/screen/position_select_screen.dart
Labels: ✨ Feature, 🎨 Design

#164 [fix] UserDto company null일 때 에러 해결
  backend/src/main/java/com/coffee/backend/utils/CustomMapper.java
Labels: :bug: Bug

#121 #64 company auth
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/lib/main.dart
  frontend/lib/screen/edit_profile_screen.dart
  frontend/lib/screen/search_company_screen.dart
  frontend/lib/screen/verify_company_screen.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/company_item.dart
  frontend/lib/widgets/rounded_img.dart
  frontend/lib/widgets/search_textfield.dart
  frontend/lib/widgets/suffix_textfield.dart
  frontend/pubspec.lock
Labels: ✨ Feature, 🎨 Design

#165 #55 chatting page 유저 id를 sender id로 해서 채팅 pub
  frontend/lib/main.dart
  frontend/lib/screen/chat_screen.dart
  frontend/lib/service/api_service.dart
Labels: ✨ Feature

#175 [FEATURE] 직무, 자기소개 수정 api #168 # 169
  backend/src/main/java/com/coffee/backend/domain/auth/service/AuthService.java
  backend/src/main/java/com/coffee/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/coffee/backend/domain/user/dto/IntroductionUpdateRequest.java
  backend/src/main/java/com/coffee/backend/domain/user/dto/PositionUpdateRequest.java
  backend/src/main/java/com/coffee/backend/domain/user/dto/UserDto.java
  backend/src/main/java/com/coffee/backend/domain/user/entity/Position.java
  backend/src/main/java/com/coffee/backend/domain/user/entity/User.java
  backend/src/main/java/com/coffee/backend/domain/user/service/UserService.java
  backend/src/main/java/com/coffee/backend/exception/ErrorCode.java
  backend/src/main/java/com/coffee/backend/utils/CustomMapper.java
Labels: ✨ Feature, 🥇 Urgency 1

#184 #34 fcm 로직 수정
  backend/src/main/java/com/coffee/backend/domain/fcm/controller/FcmController.java
  backend/src/main/java/com/coffee/backend/domain/fcm/dto/FcmPushMessageDto.java
  backend/src/main/java/com/coffee/backend/domain/fcm/service/FcmService.java
  backend/src/main/java/com/coffee/backend/domain/user/dto/UserDto.java
Labels: :bug: Bug

#189 #140 add company
  frontend/lib/screen/add_company_screen.dart
  frontend/lib/screen/search_company_screen.dart
  frontend/lib/service/api_service.dart
Labels: ✨ Feature

#191 #180 match send request
  frontend/lib/screen/cafe_details.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/choose_purpose.dart
  frontend/lib/widgets/user_item.dart
Labels: ✨ Feature

#192 #181 match info request
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/choose_purpose.dart
Labels: ✨ Feature

#196 #183 match cancel request
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/alert_dialog_widget.dart
  frontend/lib/widgets/alert_dialog_yesno_widget.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: ✨ Feature

#209 #162 fcm client
  frontend/.gitignore
  frontend/android/app/build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/settings.gradle
  frontend/ios/Runner.xcodeproj/project.pbxproj
  frontend/lib/main.dart
  frontend/lib/notification.dart
  frontend/lib/screen/alarm_list_screen.dart
  frontend/lib/screen/map_place.dart
  frontend/lib/service/api_service.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: ✨ Feature

#203 #201 map detail v2
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/screen/map_place.dart
Labels: 🔨 Refactor, ✨ Feature

#213 [feat] 프로필 수정 화면 init 시에도 유저정보 get 하기, 자기소개 수정 api 연결 #5
  frontend/lib/screen/edit_profile_screen.dart
  frontend/lib/screen/position_select_screen.dart
  frontend/lib/screen/user_screen.dart
  frontend/lib/service/api_service.dart
Labels: ✨ Feature

#193 #129 delete user
  frontend/lib/screen/settings_screen.dart
  frontend/lib/service/api_service.dart
Labels: ✨ Feature

#214 #127 select position
  frontend/lib/screen/position_select_screen.dart
  frontend/lib/service/api_service.dart
Labels: ✨ Feature

#218 #162 fcm client
  frontend/lib/kakao_login.dart
  frontend/lib/main.dart
  frontend/lib/notification.dart
  frontend/lib/screen/alarm_list_screen.dart
  frontend/lib/screen/login_screen.dart
Labels: ✨ Feature

#233 notification dialog 적용
  frontend/lib/main.dart
  frontend/lib/model/selected_index_model.dart
  frontend/lib/notification.dart
  frontend/lib/widgets/bottom_navbar.dart
  frontend/lib/widgets/dialog/notification_dialog.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: ✨ Feature, 🐱‍💻 enhance

#250 #249 send review v2
  frontend/lib/screen/coffeechat_rating_screen.dart
  frontend/lib/screen/matching_screen.dart
Labels: ✨ Feature, 🐱‍💻 enhance

#254 #251 req received
  frontend/assets/google(구글)-logo.png
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/user_item.dart
  frontend/pubspec.yaml
Labels: 🐱‍💻 enhance

#267 [fix] 상대가 요청 수락 시 푸시/인앱 알림
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/widgets/user_item.dart
Labels: :bug: Bug

#265 [fix] 요청 수락 시 chatroom으로 이동하도록 변경 #260
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/user_item.dart
Labels: ✨ Feature

#276 #264 design fix 오버플로우 수정
  frontend/lib/widgets/button/bottom_two_buttons.dart
  frontend/lib/widgets/cafe_info.dart
  frontend/lib/widgets/dialog/yn_dialog.dart
  frontend/lib/widgets/user_item.dart
Labels: :bug: Bug, 🎨 Design

#284 [feat] 매칭종료 알림 추가, dialog에 닉네임 표시 #271
  frontend/lib/notification.dart
  frontend/lib/widgets/dialog/notification_dialog.dart
Labels: ✨ Feature, 🐱‍💻 enhance

#286 #270 send request (보낸 요청 보기)
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/choose_purpose.dart
  frontend/lib/widgets/user_item.dart
Labels: :bug: Bug, ✨ Feature

#278 #277 로그아웃 시 null null 에러 해결
  frontend/lib/screen/user_screen.dart
Labels: :bug: Bug

#294 #289 one button modal
  .idea/other.xml
  frontend/lib/widgets/button/bottom_one_button.dart
  frontend/lib/widgets/choose_purpose.dart
Labels: ✨ Feature, 🎨 Design

#297 [fix] 오타 수정, company가 null일 때 처리 #296
  frontend/lib/screen/chatroom_list_screen.dart
Labels: :bug: Bug

#295 #285 profile provider
  frontend/lib/main.dart
  frontend/lib/model/user_id_model.dart
  frontend/lib/model/user_profile_model.dart
  frontend/lib/screen/add_company_screen.dart
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/edit_profile_screen.dart
  frontend/lib/screen/login_screen.dart
  frontend/lib/screen/position_select_screen.dart
  frontend/lib/screen/search_company_screen.dart
  frontend/lib/screen/user_screen.dart
  frontend/lib/screen/verify_company_screen.dart
  frontend/lib/widgets/company_item.dart
  frontend/lib/widgets/dialog/notification_dialog.dart
Labels: ✨ Feature

#300 #299 match api refactor
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/screen/matching_screen.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/alert_dialog_yesno_widget.dart
  frontend/lib/widgets/choose_purpose.dart
Labels: 🔨 Refactor

#313 [BUG] 요청 보낸 후 보낸 요청 페이지로 이동하지 않음 #312
  frontend/lib/widgets/choose_purpose.dart
Labels: :bug: Bug

#314 #305 enhance chatting
  frontend/lib/screen/chat_screen.dart
  frontend/lib/screen/chatroom_list_screen.dart
Labels: 🐱‍💻 enhance

#315 #307 dialog design
  frontend/lib/screen/add_company_screen.dart
  frontend/lib/screen/chat_screen.dart
  frontend/lib/screen/chatroom_list_screen.dart
  frontend/lib/screen/coffeechat_rating_screen.dart
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/screen/edit_profile_screen.dart
  frontend/lib/screen/login_screen.dart
  frontend/lib/screen/position_select_screen.dart
  frontend/lib/screen/search_company_screen.dart
  frontend/lib/screen/settings_screen.dart
  frontend/lib/screen/signup_screen.dart
  frontend/lib/screen/signup_screen2.dart
  frontend/lib/screen/signup_screen3.dart
  frontend/lib/screen/user_screen.dart
  frontend/lib/screen/verify_company_screen.dart
  frontend/lib/widgets/alert_dialog_widget.dart
  frontend/lib/widgets/choose_purpose.dart
  frontend/lib/widgets/dialog/one_button_dialog.dart
Labels: 🔨 Refactor, 🎨 Design

#320 #306 i accept chatroom
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/widgets/user_item.dart
Labels: ✨ Feature, 🐱‍💻 enhance

#323 #322 match cancel fix
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/widgets/dialog/yn_dialog.dart
Labels: :bug: Bug

#328 #317 accept notification goto chatroomlist
  frontend/lib/widgets/dialog/notification_dialog.dart
Labels: ✨ Feature

#335 [feat] 닉네임 변경 요청 코드 #334
  frontend/lib/screen/edit_profile_screen.dart
  frontend/lib/service/api_service.dart
Labels: ✨ Feature

#340 [feat] 채팅에 현재 디바이스의 시간대 적용 #318
  frontend/lib/screen/chat_screen.dart
Labels: ✨ Feature

#350 [feat] 종료 요청 중복 체크하는 로직 추가 #341
  frontend/lib/screen/coffeechat_rating_screen.dart
Labels: ✨ Feature, 🐱‍💻 enhance

#347 #306 i accept chatroom v2
  frontend/lib/screen/chat_screen.dart
  frontend/lib/widgets/choose_purpose.dart
  frontend/lib/widgets/user_item.dart
Labels: :bug: Bug

#354 [feat] 카카오톡 로그인 시 유저정보 프로바이더에 추가, 메인 페이지로 navigate #351
  frontend/lib/kakao_login.dart
  frontend/lib/social_login.dart
  frontend/lib/widgets/kakao_login_widget.dart
Labels: ✨ Feature

#360 #359 review update
  frontend/lib/screen/coffeechat_rating_screen.dart
  frontend/lib/screen/matching_screen.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/dialog/yn_dialog.dart
Labels: 🔨 Refactor, 🎨 Design

#369 #365 bug verification
  frontend/lib/screen/verify_company_screen.dart
Labels: :bug: Bug

#368 [refactor] 레디스 @Transactional 적용 #367
  backend/src/main/java/com/coffee/backend/domain/match/service/MatchService.java
  backend/src/main/java/com/coffee/backend/global/RedisConfig.java
Labels: 🔨 Refactor

#375 #366 bug overflow
  frontend/lib/screen/cafe_details.dart
  frontend/lib/screen/login_screen.dart
Labels: :bug: Bug

#381 [feat] 요청 확인 시 받은 요청 탭으로 이동 #376
  frontend/lib/main.dart
  frontend/lib/model/selected_index_model.dart
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/widgets/dialog/notification_dialog.dart
Labels: 🐱‍💻 enhance

#392 #389 deploy apk android
  frontend/android/app/build.gradle
  frontend/android/app/proguard-rules.pro
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_back.png
  frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_fore.png
  frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_back.png
  frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_fore.png
  frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_back.png
  frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_fore.png
  frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_back.png
  frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_fore.png
  frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_back.png
  frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_fore.png
Labels: 🌏 Deploy

#396 #393 design enhance
  frontend/lib/screen/coffeechat_rating_screen.dart
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/screen/matching_screen.dart
  frontend/lib/service/api_service.dart
  frontend/lib/widgets/choose_purpose.dart
Labels: ✨ Feature, 🐱‍💻 enhance

#397 [fix] userDetail overflow 현상 해결 #393
  frontend/lib/widgets/user/user_details.dart
Labels: :bug: Bug, 🐱‍💻 enhance

#401 #393 design enhance
  frontend/lib/screen/coffeechat_req_list.dart
  frontend/lib/widgets/choose_purpose.dart
Labels: :bug: Bug, 🎨 Design
